# Generated by Django 4.0.3 on 2023-06-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_2nd_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
