# Generated by Django 4.0.3 on 2023-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_image_2nd_url_location_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_2nd_url',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
