# Generated by Django 4.0.3 on 2023-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_location_image_2nd_url_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.TextField(null=True),
        ),
    ]
