# Generated by Django 4.0.3 on 2023-06-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_location_weather_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='location',
            name='weather_1',
        ),
        migrations.AddField(
            model_name='conference',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='weather',
            field=models.TextField(null=True),
        ),
    ]
